function unusable(a){};

    var window = {
    AbortController
    : 
    unusable,
    AbortSignal
    : 
    unusable,
    AbsoluteOrientationSensor
    : 
    unusable,
    AbstractRange
    : 
    unusable,
    Accelerometer
    : 
    unusable,
    AggregateError
    : 
    unusable,
    AnalyserNode
    : 
    unusable,
    Animation
    : 
    unusable,
    AnimationEffect
    : 
    unusable,
    AnimationEvent
    : 
    unusable,
    AnimationPlaybackEvent
    : 
    unusable,
    AnimationTimeline
    : 
    unusable,
    Array
    : 
    unusable,
    ArrayBuffer
    : 
    unusable,
    Atomics
    : 
    {load: unusable, store: unusable, add: unusable, sub: unusable, and: unusable},
    Attr
    : 
    unusable,
    Audio
    : 
    unusable,
    AudioBuffer
    : 
    unusable,
    AudioBufferSourceNode
    : 
    unusable,
    AudioContext
    : 
    unusable,
    AudioData
    : 
    unusable,
    AudioDecoder
    : 
    unusable,
    AudioDestinationNode
    : 
    unusable,
    AudioEncoder
    : 
    unusable,
    AudioListener
    : 
    unusable,
    AudioNode
    : 
    unusable,
    AudioParam
    : 
    unusable,
    AudioParamMap
    : 
    unusable,
    AudioProcessingEvent
    : 
    unusable,
    AudioScheduledSourceNode
    : 
    unusable,
    AudioWorklet
    : 
    unusable,
    AudioWorkletNode
    : 
    unusable,
    AuthenticatorAssertionResponse
    : 
    unusable,
    AuthenticatorAttestationResponse
    : 
    unusable,
    AuthenticatorResponse
    : 
    unusable,
    BackgroundFetchManager
    : 
    unusable,
    BackgroundFetchRecord
    : 
    unusable,
    BackgroundFetchRegistration
    : 
    unusable,
    BarProp
    : 
    unusable,
    BaseAudioContext
    : 
    unusable,
    BatteryManager
    : 
    unusable,
    BeforeInstallPromptEvent
    : 
    unusable,
    BeforeUnloadEvent
    : 
    unusable,
    BigInt
    : 
    unusable,
    BigInt64Array
    : 
    unusable,
    BigUint64Array
    : 
    unusable,
    BiquadFilterNode
    : 
    unusable,
    Blob
    : 
    unusable,
    BlobEvent
    : 
    unusable,
    Bluetooth
    : 
    unusable,
    BluetoothCharacteristicProperties
    : 
    unusable,
    BluetoothDevice
    : 
    unusable,
    BluetoothRemoteGATTCharacteristic
    : 
    unusable,
    BluetoothRemoteGATTDescriptor
    : 
    unusable,
    BluetoothRemoteGATTServer
    : 
    unusable,
    BluetoothRemoteGATTService
    : 
    unusable,
    BluetoothUUID
    : 
    unusable,
    Boolean
    : 
    unusable,
    BroadcastChannel
    : 
    unusable,
    BrowserCaptureMediaStreamTrack
    : 
    unusable,
    ByteLengthQueuingStrategy
    : 
    unusable,
    CDATASection
    : 
    unusable,
    CSS
    : {Hz: unusable, Q: unusable, ch: unusable, cm: unusable, deg: unusable},
    CSSAnimation
    : 
    unusable,
    CSSConditionRule
    : 
    unusable,
    CSSContainerRule
    : 
    unusable,
    CSSCounterStyleRule
    : 
    unusable,
    CSSFontFaceRule
    : 
    unusable,
    CSSFontPaletteValuesRule
    : 
    unusable,
    CSSGroupingRule
    : 
    unusable,
    CSSImageValue
    : 
    unusable,
    CSSImportRule
    : 
    unusable,
    CSSKeyframeRule
    : 
    unusable,
    CSSKeyframesRule
    : 
    unusable,
    CSSKeywordValue
    : 
    unusable,
    CSSLayerBlockRule
    : 
    unusable,
    CSSLayerStatementRule
    : 
    unusable,
    CSSMathClamp
    : 
    unusable,
    CSSMathInvert
    : 
    unusable,
    CSSMathMax
    : 
    unusable,
    CSSMathMin
    : 
    unusable,
    CSSMathNegate
    : 
    unusable,
    CSSMathProduct
    : 
    unusable,
    CSSMathSum
    : 
    unusable,
    CSSMathValue
    : 
    unusable,
    CSSMatrixComponent
    : 
    unusable,
    CSSMediaRule
    : 
    unusable,
    CSSNamespaceRule
    : 
    unusable,
    CSSNumericArray
    : 
    unusable,
    CSSNumericValue
    : 
    unusable,
    CSSPageRule
    : 
    unusable,
    CSSPerspective
    : 
    unusable,
    CSSPositionValue
    : 
    unusable,
    CSSPropertyRule
    : 
    unusable,
    CSSRotate
    : 
    unusable,
    CSSRule
    : 
    unusable,
    CSSRuleList
    : 
    unusable,
    CSSScale
    : 
    unusable,
    CSSSkew
    : 
    unusable,
    CSSSkewX
    : 
    unusable,
    CSSSkewY
    : 
    unusable,
    CSSStyleDeclaration
    : 
    unusable,
    CSSStyleRule
    : 
    unusable,
    CSSStyleSheet
    : 
    unusable,
    CSSStyleValue
    : 
    unusable,
    CSSSupportsRule
    : 
    unusable,
    CSSTransformComponent
    : 
    unusable,
    CSSTransformValue
    : 
    unusable,
    CSSTransition
    : 
    unusable,
    CSSTranslate
    : 
    unusable,
    CSSUnitValue
    : 
    unusable,
    CSSUnparsedValue
    : 
    unusable,
    CSSVariableReferenceValue
    : 
    unusable,
    Cache
    : 
    unusable,
    CacheStorage
    : 
    unusable,
    CanvasCaptureMediaStreamTrack
    : 
    unusable,
    CanvasFilter
    : 
    unusable,
    CanvasGradient
    : 
    unusable,
    CanvasPattern
    : 
    unusable,
    CanvasRenderingContext2D
    : 
    unusable,
    ChannelMergerNode
    : 
    unusable,
    ChannelSplitterNode
    : 
    unusable,
    CharacterData
    : 
    unusable,
    Clipboard
    : 
    unusable,
    ClipboardEvent
    : 
    unusable,
    ClipboardItem
    : 
    unusable,
    CloseEvent
    : 
    unusable,
    Comment
    : 
    unusable,
    CompositionEvent
    : 
    unusable,
    CompressionStream
    : 
    unusable,
    ConstantSourceNode
    : 
    unusable,
    ConvolverNode
    : 
    unusable,
    CookieChangeEvent
    : 
    unusable,
    CookieStore
    : 
    unusable,
    CookieStoreManager
    : 
    unusable,
    CountQueuingStrategy
    : 
    unusable,
    Credential
    : 
    unusable,
    CredentialsContainer
    : 
    unusable,
    CropTarget
    : 
    unusable,
    Crypto
    : 
    unusable,
    CryptoKey
    : 
    unusable,
    CustomElementRegistry
    : 
    unusable,
    CustomEvent
    : 
    unusable,
    CustomStateSet
    : 
    unusable,
    DOMError
    : 
    unusable,
    DOMException
    : 
    unusable,
    DOMImplementation
    : 
    unusable,
    DOMMatrix
    : 
    unusable,
    DOMMatrixReadOnly
    : 
    unusable,
    DOMParser
    : 
    unusable,
    DOMPoint
    : 
    unusable,
    DOMPointReadOnly
    : 
    unusable,
    DOMQuad
    : 
    unusable,
    DOMRect
    : 
    unusable,
    DOMRectList
    : 
    unusable,
    DOMRectReadOnly
    : 
    unusable,
    DOMStringList
    : 
    unusable,
    DOMStringMap
    : 
    unusable,
    DOMTokenList
    : 
    unusable,
    DataTransfer
    : 
    unusable,
    DataTransferItem
    : 
    unusable,
    DataTransferItemList
    : 
    unusable,
    DataView
    : 
    unusable,
    Date
    : 
    unusable,
    DecompressionStream
    : 
    unusable,
    DelayNode
    : 
    unusable,
    DelegatedInkTrailPresenter
    : 
    unusable,
    DeviceMotionEvent
    : 
    unusable,
    DeviceMotionEventAcceleration
    : 
    unusable,
    DeviceMotionEventRotationRate
    : 
    unusable,
    DeviceOrientationEvent
    : 
    unusable,
    Document
    : 
    unusable,
    DocumentFragment
    : 
    unusable,
    DocumentTimeline
    : 
    unusable,
    DocumentType
    : 
    unusable,
    DragEvent
    : 
    unusable,
    DynamicsCompressorNode
    : 
    unusable,
    Element
    : 
    unusable,
    ElementInternals
    : 
    unusable,
    EncodedAudioChunk
    : 
    unusable,
    EncodedVideoChunk
    : 
    unusable,
    Error
    : 
    unusable,
    ErrorEvent
    : 
    unusable,
    EvalError
    : 
    unusable,
    Event
    : 
    unusable,
    EventCounts
    : 
    unusable,
    EventSource
    : 
    unusable,
    EventTarget
    : 
    unusable,
    External
    : 
    unusable,
    EyeDropper
    : 
    unusable,
    FeaturePolicy
    : 
    unusable,
    FederatedCredential
    : 
    unusable,
    File
    : 
    unusable,
    FileList
    : 
    unusable,
    FileReader
    : 
    unusable,
    FileSystemDirectoryHandle
    : 
    unusable,
    FileSystemFileHandle
    : 
    unusable,
    FileSystemHandle
    : 
    unusable,
    FileSystemWritableFileStream
    : 
    unusable,
    FinalizationRegistry
    : 
    unusable,
    Float32Array
    : 
    unusable,
    Float64Array
    : 
    unusable,
    FocusEvent
    : 
    unusable,
    FontData
    : 
    unusable,
    FontFace
    : 
    unusable,
    FontFaceSetLoadEvent
    : 
    unusable,
    FormData
    : 
    unusable,
    FormDataEvent
    : 
    unusable,
    FragmentDirective
    : 
    unusable,
    Function
    : 
    unusable,
    GainNode
    : 
    unusable,
    Gamepad
    : 
    unusable,
    GamepadButton
    : 
    unusable,
    GamepadEvent
    : 
    unusable,
    GamepadHapticActuator
    : 
    unusable,
    Geolocation
    : 
    unusable,
    GeolocationCoordinates
    : 
    unusable,
    GeolocationPosition
    : 
    unusable,
    GeolocationPositionError
    : 
    unusable,
    GravitySensor
    : 
    unusable,
    Gyroscope
    : 
    unusable,
    HID
    : 
    unusable,
    HIDConnectionEvent
    : 
    unusable,
    HIDDevice
    : 
    unusable,
    HIDInputReportEvent
    : 
    unusable,
    HTMLAllCollection
    : 
    unusable,
    HTMLAnchorElement
    : 
    unusable,
    HTMLAreaElement
    : 
    unusable,
    HTMLAudioElement
    : 
    unusable,
    HTMLBRElement
    : 
    unusable,
    HTMLBaseElement
    : 
    unusable,
    HTMLBodyElement
    : 
    unusable,
    HTMLButtonElement
    : 
    unusable,
    HTMLCanvasElement
    : 
    unusable,
    HTMLCollection
    : 
    unusable,
    HTMLDListElement
    : 
    unusable,
    HTMLDataElement
    : 
    unusable,
    HTMLDataListElement
    : 
    unusable,
    HTMLDetailsElement
    : 
    unusable,
    HTMLDialogElement
    : 
    unusable,
    HTMLDirectoryElement
    : 
    unusable,
    HTMLDivElement
    : 
    unusable,
    HTMLDocument
    : 
    unusable,
    HTMLElement
    : 
    unusable,
    HTMLEmbedElement
    : 
    unusable,
    HTMLFieldSetElement
    : 
    unusable,
    HTMLFontElement
    : 
    unusable,
    HTMLFormControlsCollection
    : 
    unusable,
    HTMLFormElement
    : 
    unusable,
    HTMLFrameElement
    : 
    unusable,
    HTMLFrameSetElement
    : 
    unusable,
    HTMLHRElement
    : 
    unusable,
    HTMLHeadElement
    : 
    unusable,
    HTMLHeadingElement
    : 
    unusable,
    HTMLHtmlElement
    : 
    unusable,
    HTMLIFrameElement
    : 
    unusable,
    HTMLImageElement
    : 
    unusable,
    HTMLInputElement
    : 
    unusable,
    HTMLLIElement
    : 
    unusable,
    HTMLLabelElement
    : 
    unusable,
    HTMLLegendElement
    : 
    unusable,
    HTMLLinkElement
    : 
    unusable,
    HTMLMapElement
    : 
    unusable,
    HTMLMarqueeElement
    : 
    unusable,
    HTMLMediaElement
    : 
    unusable,
    HTMLMenuElement
    : 
    unusable,
    HTMLMetaElement
    : 
    unusable,
    HTMLMeterElement
    : 
    unusable,
    HTMLModElement
    : 
    unusable,
    HTMLOListElement
    : 
    unusable,
    HTMLObjectElement
    : 
    unusable,
    HTMLOptGroupElement
    : 
    unusable,
    HTMLOptionElement
    : 
    unusable,
    HTMLOptionsCollection
    : 
    unusable,
    HTMLOutputElement
    : 
    unusable,
    HTMLParagraphElement
    : 
    unusable,
    HTMLParamElement
    : 
    unusable,
    HTMLPictureElement
    : 
    unusable,
    HTMLPreElement
    : 
    unusable,
    HTMLProgressElement
    : 
    unusable,
    HTMLQuoteElement
    : 
    unusable,
    HTMLScriptElement
    : 
    unusable,
    HTMLSelectElement
    : 
    unusable,
    HTMLSlotElement
    : 
    unusable,
    HTMLSourceElement
    : 
    unusable,
    HTMLSpanElement
    : 
    unusable,
    HTMLStyleElement
    : 
    unusable,
    HTMLTableCaptionElement
    : 
    unusable,
    HTMLTableCellElement
    : 
    unusable,
    HTMLTableColElement
    : 
    unusable,
    HTMLTableElement
    : 
    unusable,
    HTMLTableRowElement
    : 
    unusable,
    HTMLTableSectionElement
    : 
    unusable,
    HTMLTemplateElement
    : 
    unusable,
    HTMLTextAreaElement
    : 
    unusable,
    HTMLTimeElement
    : 
    unusable,
    HTMLTitleElement
    : 
    unusable,
    HTMLTrackElement
    : 
    unusable,
    HTMLUListElement
    : 
    unusable,
    HTMLUnknownElement
    : 
    unusable,
    HTMLVideoElement
    : 
    unusable,
    HashChangeEvent
    : 
    unusable,
    Headers
    : 
    unusable,
    Highlight
    : 
    unusable,
    HighlightRegistry
    : 
    unusable,
    History
    : 
    unusable,
    IDBCursor
    : 
    unusable,
    IDBCursorWithValue
    : 
    unusable,
    IDBDatabase
    : 
    unusable,
    IDBFactory
    : 
    unusable,
    IDBIndex
    : 
    unusable,
    IDBKeyRange
    : 
    unusable,
    IDBObjectStore
    : 
    unusable,
    IDBOpenDBRequest
    : 
    unusable,
    IDBRequest
    : 
    unusable,
    IDBTransaction
    : 
    unusable,
    IDBVersionChangeEvent
    : 
    unusable,
    IIRFilterNode
    : 
    unusable,
    IdleDeadline
    : 
    unusable,
    IdleDetector
    : 
    unusable,
    Image
    : 
    unusable,
    ImageBitmap
    : 
    unusable,
    ImageBitmapRenderingContext
    : 
    unusable,
    ImageCapture
    : 
    unusable,
    ImageData
    : 
    unusable,
    ImageDecoder
    : 
    unusable,
    ImageTrack
    : 
    unusable,
    ImageTrackList
    : 
    unusable,
    Ink
    : 
    unusable,
    InputDeviceCapabilities
    : 
    unusable,
    InputDeviceInfo
    : 
    unusable,
    InputEvent
    : 
    unusable,
    Int8Array
    : 
    unusable,
    Int16Array
    : 
    unusable,
    Int32Array
    : 
    unusable,
    IntersectionObserver
    : 
    unusable,
    IntersectionObserverEntry
    : 
    unusable,
    Intl
    : 
    {getCanonicalLocales: unusable, supportedValuesOf: unusable, DateTimeFormat: unusable, NumberFormat: unusable, Collator: unusable},
    
    Keyboard
    : 
    unusable,
    KeyboardEvent
    : 
    unusable,
    KeyboardLayoutMap
    : 
    unusable,
    KeyframeEffect
    : 
    unusable,
    LargestContentfulPaint
    : 
    unusable,
    LaunchParams
    : 
    unusable,
    LaunchQueue
    : 
    unusable,
    LayoutShift
    : 
    unusable,
    LayoutShiftAttribution
    : 
    unusable,
    LinearAccelerationSensor
    : 
    unusable,
    Location
    : 
    unusable,
    Lock
    : 
    unusable,
    LockManager
    : 
    unusable,
    MIDIAccess
    : 
    unusable,
    MIDIConnectionEvent
    : 
    unusable,
    MIDIInput
    : 
    unusable,
    MIDIInputMap
    : 
    unusable,
    MIDIMessageEvent
    : 
    unusable,
    MIDIOutput
    : 
    unusable,
    MIDIOutputMap
    : 
    unusable,
    MIDIPort
    : 
    unusable,
    Map
    : 
    unusable,
    Math
    : 
    {abs: unusable, acos: unusable, acosh: unusable, asin: unusable, asinh: unusable},
    MediaCapabilities
    : 
    unusable,
    MediaDeviceInfo
    : 
    unusable,
    MediaDevices
    : 
    unusable,
    MediaElementAudioSourceNode
    : 
    unusable,
    MediaEncryptedEvent
    : 
    unusable,
    MediaError
    : 
    unusable,
    MediaKeyMessageEvent
    : 
    unusable,
    MediaKeySession
    : 
    unusable,
    MediaKeyStatusMap
    : 
    unusable,
    MediaKeySystemAccess
    : 
    unusable,
    MediaKeys
    : 
    unusable,
    MediaList
    : 
    unusable,
    MediaMetadata
    : 
    unusable,
    MediaQueryList
    : 
    unusable,
    MediaQueryListEvent
    : 
    unusable,
    MediaRecorder
    : 
    unusable,
    MediaSession
    : 
    unusable,
    MediaSource
    : 
    unusable,
    MediaStream
    : 
    unusable,
    MediaStreamAudioDestinationNode
    : 
    unusable,
    MediaStreamAudioSourceNode
    : 
    unusable,
    MediaStreamEvent
    : 
    unusable,
    MediaStreamTrack
    : 
    unusable,
    MediaStreamTrackEvent
    : 
    unusable,
    MediaStreamTrackGenerator
    : 
    unusable,
    MediaStreamTrackProcessor
    : 
    unusable,
    MessageChannel
    : 
    unusable,
    MessageEvent
    : 
    unusable,
    MessagePort
    : 
    unusable,
    MimeType
    : 
    unusable,
    MimeTypeArray
    : 
    unusable,
    MouseEvent
    : 
    unusable,
    MutationEvent
    : 
    unusable,
    MutationObserver
    : 
    unusable,
    MutationRecord
    : 
    unusable,
    NaN
    : 
    NaN,
    NamedNodeMap
    : 
    unusable,
    NavigateEvent
    : 
    unusable,
    Navigation
    : 
    unusable,
    NavigationCurrentEntryChangeEvent
    : 
    unusable,
    NavigationDestination
    : 
    unusable,
    NavigationHistoryEntry
    : 
    unusable,
    NavigationPreloadManager
    : 
    unusable,
    NavigationTransition
    : 
    unusable,
    Navigator
    : 
    unusable,
    NavigatorManagedData
    : 
    unusable,
    NavigatorUAData
    : 
    unusable,
    NetworkInformation
    : 
    unusable,
    Node
    : 
    unusable,
    NodeFilter
    : 
    unusable,
    NodeIterator
    : 
    unusable,
    NodeList
    : 
    unusable,
    Notification
    : 
    unusable,
    Number
    : 
    unusable,
    OTPCredential
    : 
    unusable,
    Object
    : 
    unusable,
    OfflineAudioCompletionEvent
    : 
    unusable,
    OfflineAudioContext
    : 
    unusable,
    OffscreenCanvas
    : 
    unusable,
    OffscreenCanvasRenderingContext2D
    : 
    unusable,
    Option
    : 
    unusable,
    OrientationSensor
    : 
    unusable,
    OscillatorNode
    : 
    unusable,
    OverconstrainedError
    : 
    unusable,
    PageTransitionEvent
    : 
    unusable,
    PannerNode
    : 
    unusable,
    PasswordCredential
    : 
    unusable,
    Path2D
    : 
    unusable,
    PaymentAddress
    : 
    unusable,
    PaymentInstruments
    : 
    unusable,
    PaymentManager
    : 
    unusable,
    PaymentMethodChangeEvent
    : 
    unusable,
    PaymentRequest
    : 
    unusable,
    PaymentRequestUpdateEvent
    : 
    unusable,
    PaymentResponse
    : 
    unusable,
    Performance
    : 
    unusable,
    PerformanceElementTiming
    : 
    unusable,
    PerformanceEntry
    : 
    unusable,
    PerformanceEventTiming
    : 
    unusable,
    PerformanceLongTaskTiming
    : 
    unusable,
    PerformanceMark
    : 
    unusable,
    PerformanceMeasure
    : 
    unusable,
    PerformanceNavigation
    : 
    unusable,
    PerformanceNavigationTiming
    : 
    unusable,
    PerformanceObserver
    : 
    unusable,
    PerformanceObserverEntryList
    : 
    unusable,
    PerformancePaintTiming
    : 
    unusable,
    PerformanceResourceTiming
    : 
    unusable,
    PerformanceServerTiming
    : 
    unusable,
    PerformanceTiming
    : 
    unusable,
    PeriodicSyncManager
    : 
    unusable,
    PeriodicWave
    : 
    unusable,
    PermissionStatus
    : 
    unusable,
    Permissions
    : 
    unusable,
    PictureInPictureEvent
    : 
    unusable,
    PictureInPictureWindow
    : 
    unusable,
    Plugin
    : 
    unusable,
    PluginArray
    : 
    unusable,
    PointerEvent
    : 
    unusable,
    PopStateEvent
    : 
    unusable,
    Presentation
    : 
    unusable,
    PresentationAvailability
    : 
    unusable,
    PresentationConnection
    : 
    unusable,
    PresentationConnectionAvailableEvent
    : 
    unusable,
    PresentationConnectionCloseEvent
    : 
    unusable,
    PresentationConnectionList
    : 
    unusable,
    PresentationReceiver
    : 
    unusable,
    PresentationRequest
    : 
    unusable,
    ProcessingInstruction
    : 
    unusable,
    Profiler
    : 
    unusable,
    ProgressEvent
    : 
    unusable,
    Promise
    : 
    unusable,
    PromiseRejectionEvent
    : 
    unusable,
    Proxy
    : 
    unusable,
    PublicKeyCredential
    : 
    unusable,
    PushManager
    : 
    unusable,
    PushSubscription
    : 
    unusable,
    PushSubscriptionOptions
    : 
    unusable,
    RTCCertificate
    : 
    unusable,
    RTCDTMFSender
    : 
    unusable,
    RTCDTMFToneChangeEvent
    : 
    unusable,
    RTCDataChannel
    : 
    unusable,
    RTCDataChannelEvent
    : 
    unusable,
    RTCDtlsTransport
    : 
    unusable,
    RTCEncodedAudioFrame
    : 
    unusable,
    RTCEncodedVideoFrame
    : 
    unusable,
    RTCError
    : 
    unusable,
    RTCErrorEvent
    : 
    unusable,
    RTCIceCandidate
    : 
    unusable,
    RTCIceTransport
    : 
    unusable,
    RTCPeerConnection
    : 
    unusable,
    RTCPeerConnectionIceErrorEvent
    : 
    unusable,
    RTCPeerConnectionIceEvent
    : 
    unusable,
    RTCRtpReceiver
    : 
    unusable,
    RTCRtpSender
    : 
    unusable,
    RTCRtpTransceiver
    : 
    unusable,
    RTCSctpTransport
    : 
    unusable,
    RTCSessionDescription
    : 
    unusable,
    RTCStatsReport
    : 
    unusable,
    RTCTrackEvent
    : 
    unusable,
    RadioNodeList
    : 
    unusable,
    Range
    : 
    unusable,
    RangeError
    : 
    unusable,
    ReadableByteStreamController
    : 
    unusable,
    ReadableStream
    : 
    unusable,
    ReadableStreamBYOBReader
    : 
    unusable,
    ReadableStreamBYOBRequest
    : 
    unusable,
    ReadableStreamDefaultController
    : 
    unusable,
    ReadableStreamDefaultReader
    : 
    unusable,
    ReferenceError
    : 
    unusable,
    Reflect
    : 
    {defineProperty: unusable, deleteProperty: unusable, apply: unusable, construct: unusable, get: unusable},
    RegExp
    : 
    unusable,
    RelativeOrientationSensor
    : 
    unusable,
    RemotePlayback
    : 
    unusable,
    ReportingObserver
    : 
    unusable,
    Request
    : 
    unusable,
    ResizeObserver
    : 
    unusable,
    ResizeObserverEntry
    : 
    unusable,
    ResizeObserverSize
    : 
    unusable,
    Response
    : 
    unusable,
    SVGAElement
    : 
    unusable,
    SVGAngle
    : 
    unusable,
    SVGAnimateElement
    : 
    unusable,
    SVGAnimateMotionElement
    : 
    unusable,
    SVGAnimateTransformElement
    : 
    unusable,
    SVGAnimatedAngle
    : 
    unusable,
    SVGAnimatedBoolean
    : 
    unusable,
    SVGAnimatedEnumeration
    : 
    unusable,
    SVGAnimatedInteger
    : 
    unusable,
    SVGAnimatedLength
    : 
    unusable,
    SVGAnimatedLengthList
    : 
    unusable,
    SVGAnimatedNumber
    : 
    unusable,
    SVGAnimatedNumberList
    : 
    unusable,
    SVGAnimatedPreserveAspectRatio
    : 
    unusable,
    SVGAnimatedRect
    : 
    unusable,
    SVGAnimatedString
    : 
    unusable,
    SVGAnimatedTransformList
    : 
    unusable,
    SVGAnimationElement
    : 
    unusable,
    SVGCircleElement
    : 
    unusable,
    SVGClipPathElement
    : 
    unusable,
    SVGComponentTransferFunctionElement
    : 
    unusable,
    SVGDefsElement
    : 
    unusable,
    SVGDescElement
    : 
    unusable,
    SVGElement
    : 
    unusable,
    SVGEllipseElement
    : 
    unusable,
    SVGFEBlendElement
    : 
    unusable,
    SVGFEColorMatrixElement
    : 
    unusable,
    SVGFEComponentTransferElement
    : 
    unusable,
    SVGFECompositeElement
    : 
    unusable,
    SVGFEConvolveMatrixElement
    : 
    unusable,
    SVGFEDiffuseLightingElement
    : 
    unusable,
    SVGFEDisplacementMapElement
    : 
    unusable,
    SVGFEDistantLightElement
    : 
    unusable,
    SVGFEDropShadowElement
    : 
    unusable,
    SVGFEFloodElement
    : 
    unusable,
    SVGFEFuncAElement
    : 
    unusable,
    SVGFEFuncBElement
    : 
    unusable,
    SVGFEFuncGElement
    : 
    unusable,
    SVGFEFuncRElement
    : 
    unusable,
    SVGFEGaussianBlurElement
    : 
    unusable,
    SVGFEImageElement
    : 
    unusable,
    SVGFEMergeElement
    : 
    unusable,
    SVGFEMergeNodeElement
    : 
    unusable,
    SVGFEMorphologyElement
    : 
    unusable,
    SVGFEOffsetElement
    : 
    unusable,
    SVGFEPointLightElement
    : 
    unusable,
    SVGFESpecularLightingElement
    : 
    unusable,
    SVGFESpotLightElement
    : 
    unusable,
    SVGFETileElement
    : 
    unusable,
    SVGFETurbulenceElement
    : 
    unusable,
    SVGFilterElement
    : 
    unusable,
    SVGForeignObjectElement
    : 
    unusable,
    SVGGElement
    : 
    unusable,
    SVGGeometryElement
    : 
    unusable,
    SVGGradientElement
    : 
    unusable,
    SVGGraphicsElement
    : 
    unusable,
    SVGImageElement
    : 
    unusable,
    SVGLength
    : 
    unusable,
    SVGLengthList
    : 
    unusable,
    SVGLineElement
    : 
    unusable,
    SVGLinearGradientElement
    : 
    unusable,
    SVGMPathElement
    : 
    unusable,
    SVGMarkerElement
    : 
    unusable,
    SVGMaskElement
    : 
    unusable,
    SVGMatrix
    : 
    unusable,
    SVGMetadataElement
    : 
    unusable,
    SVGNumber
    : 
    unusable,
    SVGNumberList
    : 
    unusable,
    SVGPathElement
    : 
    unusable,
    SVGPatternElement
    : 
    unusable,
    SVGPoint
    : 
    unusable,
    SVGPointList
    : 
    unusable,
    SVGPolygonElement
    : 
    unusable,
    SVGPolylineElement
    : 
    unusable,
    SVGPreserveAspectRatio
    : 
    unusable,
    SVGRadialGradientElement
    : 
    unusable,
    SVGRect
    : 
    unusable,
    SVGRectElement
    : 
    unusable,
    SVGSVGElement
    : 
    unusable,
    SVGScriptElement
    : 
    unusable,
    SVGSetElement
    : 
    unusable,
    SVGStopElement
    : 
    unusable,
    SVGStringList
    : 
    unusable,
    SVGStyleElement
    : 
    unusable,
    SVGSwitchElement
    : 
    unusable,
    SVGSymbolElement
    : 
    unusable,
    SVGTSpanElement
    : 
    unusable,
    SVGTextContentElement
    : 
    unusable,
    SVGTextElement
    : 
    unusable,
    SVGTextPathElement
    : 
    unusable,
    SVGTextPositioningElement
    : 
    unusable,
    SVGTitleElement
    : 
    unusable,
    SVGTransform
    : 
    unusable,
    SVGTransformList
    : 
    unusable,
    SVGUnitTypes
    : 
    unusable,
    SVGUseElement
    : 
    unusable,
    SVGViewElement
    : 
    unusable,
    Sanitizer
    : 
    unusable,
    Scheduler
    : 
    unusable,
    Scheduling
    : 
    unusable,
    Screen
    : 
    unusable,
    ScreenDetailed
    : 
    unusable,
    ScreenDetails
    : 
    unusable,
    ScreenOrientation
    : 
    unusable,
    ScriptProcessorNode
    : 
    unusable,
    SecurityPolicyViolationEvent
    : 
    unusable,
    Selection
    : 
    unusable,
    Sensor
    : 
    unusable,
    SensorErrorEvent
    : 
    unusable,
    Serial
    : 
    unusable,
    SerialPort
    : 
    unusable,
    ServiceWorker
    : 
    unusable,
    ServiceWorkerContainer
    : 
    unusable,
    ServiceWorkerRegistration
    : 
    unusable,
    Set
    : 
    unusable,
    ShadowRoot
    : 
    unusable,
    SharedWorker
    : 
    unusable,
    SourceBuffer
    : 
    unusable,
    SourceBufferList
    : 
    unusable,
    SpeechSynthesisErrorEvent
    : 
    unusable,
    SpeechSynthesisEvent
    : 
    unusable,
    SpeechSynthesisUtterance
    : 
    unusable,
    StaticRange
    : 
    unusable,
    StereoPannerNode
    : 
    unusable,
    Storage
    : 
    unusable,
    StorageEvent
    : 
    unusable,
    StorageManager
    : 
    unusable,
    String
    : 
    unusable,
    StylePropertyMap
    : 
    unusable,
    StylePropertyMapReadOnly
    : 
    unusable,
    StyleSheet
    : 
    unusable,
    StyleSheetList
    : 
    unusable,
    SubmitEvent
    : 
    unusable,
    SubtleCrypto
    : 
    unusable,
    Symbol
    : 
    unusable,
    SyncManager
    : 
    unusable,
    SyntaxError
    : 
    unusable,
    TaskAttributionTiming
    : 
    unusable,
    TaskController
    : 
    unusable,
    TaskPriorityChangeEvent
    : 
    unusable,
    TaskSignal
    : 
    unusable,
    Text
    : 
    unusable,
    TextDecoder
    : 
    unusable,
    TextDecoderStream
    : 
    unusable,
    TextEncoder
    : 
    unusable,
    TextEncoderStream
    : 
    unusable,
    TextEvent
    : 
    unusable,
    TextMetrics
    : 
    unusable,
    TextTrack
    : 
    unusable,
    TextTrackCue
    : 
    unusable,
    TextTrackCueList
    : 
    unusable,
    TextTrackList
    : 
    unusable,
    TimeRanges
    : 
    unusable,
    Touch
    : 
    unusable,
    TouchEvent
    : 
    unusable,
    TouchList
    : 
    unusable,
    TrackEvent
    : 
    unusable,
    TransformStream
    : 
    unusable,
    TransformStreamDefaultController
    : 
    unusable,
    TransitionEvent
    : 
    unusable,
    TreeWalker
    : 
    unusable,
    TrustedHTML
    : 
    unusable,
    TrustedScript
    : 
    unusable,
    TrustedScriptURL
    : 
    unusable,
    TrustedTypePolicy
    : 
    unusable,
    TrustedTypePolicyFactory
    : 
    unusable,
    TypeError
    : 
    unusable,
    UIEvent
    : 
    unusable,
    URIError
    : 
    unusable,
    URL
    : 
    unusable,
    URLPattern
    : 
    unusable,
    URLSearchParams
    : 
    unusable,
    USB
    : 
    unusable,
    USBAlternateInterface
    : 
    unusable,
    USBConfiguration
    : 
    unusable,
    USBConnectionEvent
    : 
    unusable,
    USBDevice
    : 
    unusable,
    USBEndpoint
    : 
    unusable,
    USBInTransferResult
    : 
    unusable,
    USBInterface
    : 
    unusable,
    USBIsochronousInTransferPacket
    : 
    unusable,
    USBIsochronousInTransferResult
    : 
    unusable,
    USBIsochronousOutTransferPacket
    : 
    unusable,
    USBIsochronousOutTransferResult
    : 
    unusable,
    USBOutTransferResult
    : 
    unusable,
    Uint8Array
    : 
    unusable,
    Uint8ClampedArray
    : 
    unusable,
    Uint16Array
    : 
    unusable,
    Uint32Array
    : 
    unusable,
    UserActivation
    : 
    unusable,
    VTTCue
    : 
    unusable,
    ValidityState
    : 
    unusable,
    VideoColorSpace
    : 
    unusable,
    VideoDecoder
    : 
    unusable,
    VideoEncoder
    : 
    unusable,
    VideoFrame
    : 
    unusable,
    VideoPlaybackQuality
    : 
    unusable,
    VirtualKeyboard
    : 
    unusable,
    VirtualKeyboardGeometryChangeEvent
    : 
    unusable,
    VisualViewport
    : 
    unusable,
    WakeLock
    : 
    unusable,
    WakeLockSentinel
    : 
    unusable,
    WaveShaperNode
    : 
    unusable,
    WeakMap
    : 
    unusable,
    WeakRef
    : 
    unusable,
    WeakSet
    : 
    unusable,
    WebAssembly
    : 
    {compile: unusable, validate: unusable, instantiate: unusable, compileStreaming: unusable, instantiateStreaming: unusable},
    WebGL2RenderingContext
    : 
    unusable,
    WebGLActiveInfo
    : 
    unusable,
    WebGLBuffer
    : 
    unusable,
    WebGLContextEvent
    : 
    unusable,
    WebGLFramebuffer
    : 
    unusable,
    WebGLProgram
    : 
    unusable,
    WebGLQuery
    : 
    unusable,
    WebGLRenderbuffer
    : 
    unusable,
    WebGLRenderingContext
    : 
    unusable,
    WebGLSampler
    : 
    unusable,
    WebGLShader
    : 
    unusable,
    WebGLShaderPrecisionFormat
    : 
    unusable,
    WebGLSync
    : 
    unusable,
    WebGLTexture
    : 
    unusable,
    WebGLTransformFeedback
    : 
    unusable,
    WebGLUniformLocation
    : 
    unusable,
    WebGLVertexArrayObject
    : 
    unusable,
    WebKitCSSMatrix
    : 
    unusable,
    WebKitMutationObserver
    : 
    unusable,
    WebSocket
    : 
    unusable,
    WebTransport
    : 
    unusable,
    WebTransportBidirectionalStream
    : 
    unusable,
    WebTransportDatagramDuplexStream
    : 
    unusable,
    WebTransportError
    : 
    unusable,
    WheelEvent
    : 
    unusable,
    Window
    : 
    unusable,
    WindowControlsOverlay
    : 
    unusable,
    WindowControlsOverlayGeometryChangeEvent
    : 
    unusable,
    Worker
    : 
    unusable,
    Worklet
    : 
    unusable,
    WritableStream
    : 
    unusable,
    WritableStreamDefaultController
    : 
    unusable,
    WritableStreamDefaultWriter
    : 
    unusable,
    XMLDocument
    : 
    unusable,
    XMLHttpRequestEventTarget
    : 
    unusable,
    XMLHttpRequestUpload
    : 
    unusable,
    XMLSerializer
    : 
    unusable,
    XPathEvaluator
    : 
    unusable,
    XPathExpression
    : 
    unusable,
    XPathResult
    : 
    unusable,
    XRAnchor
    : 
    unusable,
    XRAnchorSet
    : 
    unusable,
    XRBoundedReferenceSpace
    : 
    unusable,
    XRCPUDepthInformation
    : 
    unusable,
    XRDOMOverlayState
    : 
    unusable,
    XRDepthInformation
    : 
    unusable,
    XRFrame
    : 
    unusable,
    XRHitTestResult
    : 
    unusable,
    XRHitTestSource
    : 
    unusable,
    XRInputSource
    : 
    unusable,
    XRInputSourceArray
    : 
    unusable,
    XRInputSourceEvent
    : 
    unusable,
    XRInputSourcesChangeEvent
    : 
    unusable,
    XRLayer
    : 
    unusable,
    XRLightEstimate
    : 
    unusable,
    XRLightProbe
    : 
    unusable,
    XRPose
    : 
    unusable,
    XRRay
    : 
    unusable,
    XRReferenceSpace
    : 
    unusable,
    XRReferenceSpaceEvent
    : 
    unusable,
    XRRenderState
    : 
    unusable,
    XRRigidTransform
    : 
    unusable,
    XRSession
    : 
    unusable,
    XRSessionEvent
    : 
    unusable,
    XRSpace
    : 
    unusable,
    XRSystem
    : 
    unusable,
    XRTransientInputHitTestResult
    : 
    unusable,
    XRTransientInputHitTestSource
    : 
    unusable,
    XRView
    : 
    unusable,
    XRViewerPose
    : 
    unusable,
    XRViewport
    : 
    unusable,
    XRWebGLBinding
    : 
    unusable,
    XRWebGLDepthInformation
    : 
    unusable,
    XRWebGLLayer
    : 
    unusable,
    XSLTProcessor
    : 
    unusable,
    decodeURI
    : 
    unusable,
    decodeURIComponent
    : 
    unusable,
    encodeURI
    : 
    unusable,
    encodeURIComponent
    : 
    unusable,
    escape
    : 
    unusable,
    eval
    : 
    unusable,
    event
    : 
    undefined,
    isFinite
    : 
    unusable,
    isNaN
    : 
    unusable,
    offscreenBuffering
    : 
    true,
    parseFloat
    : 
    unusable,
    parseInt
    : 
    unusable,
    undefined
    : 
    undefined,
    unescape
    : 
    unusable,
    webkitMediaStream
    : 
    unusable,
    webkitRTCPeerConnection
    : 
    unusable,
    webkitSpeechGrammar
    : 
    unusable,
    webkitSpeechGrammarList
    : 
    unusable,
    webkitSpeechRecognition
    : 
    unusable,
    webkitSpeechRecognitionError
    : 
    unusable,
    webkitSpeechRecognitionEvent
    : 
    unusable,
    webkitURL
    : 
    unusable,
    
    ...require("./api/a")(unusable),
    ...require("./api/c")(unusable),
    ...require("./api/f")(unusable),
    ...require("./api/s")(unusable),
    ...require("./api/x")(unusable),
    document:require("./api/doc")(unusable),
    
    }
    
    
var windowDocumentEvents= [
"onabort",
"onanimationend",
"onanimationiteration",
"onanimationstart",
"onauxclick",
"onbeforecopy",
"onbeforecut",
"onbeforeinput",
"onbeforematch",
"onbeforepaste",
"onbeforexrselect",
"onblur",
"oncancel",
"oncanplay",
"oncanplaythrough",
"onchange",
"onclick",
"onclose",
"oncontextlost",
"oncontextmenu",
"oncontextrestored",
"oncopy",
"oncuechange",
"oncut",
"ondblclick",
"ondrag",
"ondragend",
"ondragenter",
"ondragleave",
"ondragover",
"ondragstart",
"ondrop",
"ondurationchange",
"onemptied",
"onended",
"onerror",
"onfocus",
"onformdata",
"onfreeze",
"onfullscreenchange",
"onfullscreenerror",
"ongotpointercapture",
"oninput",
"oninvalid",
"onkeydown",
"onkeypress",
"onkeyup",
"onload",
"onloadeddata",
"onloadedmetadata",
"onloadstart",
"onlostpointercapture",
"onmousedown",
"onmouseenter",
"onmouseleave",
"onmousemove",
"onmouseout",
"onmouseover",
"onmouseup",
"onmousewheel",
"onpaste",
"onpause",
"onplay",
"onplaying",
"onpointercancel",
"onpointerdown",
"onpointerenter",
"onpointerleave",
"onpointerlockchange",
"onpointerlockerror",
"onpointermove",
"onpointerout",
"onpointerover",
"onpointerrawupdate",
"onpointerup",
"onprerenderingchange",
"onprogress",
"onratechange",
"onreadystatechange",
"onreset",
"onresize",
"onresume",
"onscroll",
"onsearch",
"onsecuritypolicyviolation",
"onseeked",
"onseeking",
"onselect",
"onselectionchange",
"onselectstart",
"onslotchange",
"onstalled",
"onsubmit",
"onsuspend",
"ontimeupdate",
"ontoggle",
"ontransitioncancel",
"ontransitionend",
"ontransitionrun",
"ontransitionstart",
"onvisibilitychange",
"onvolumechange",
"onwaiting",
"onwebkitanimationend",
"onwebkitanimationiteration",
"onwebkitanimationstart",
"onwebkitfullscreenchange",
"onwebkitfullscreenerror",
"onwebkittransitionend",
"onwheel"
];
function IgnoreEventhandlers(obj){
    var i;
    for(i=0;i<windowDocumentEvents.length;i++){
        Object.defineProperty(obj,windowDocumentEvents[i],{
            set:unusable,
            get:unusable
        });
    }
}


IgnoreEventhandlers(window);
IgnoreEventhandlers(window.document);


module.exports = window;